CC := gcc
#CFLAGS := -O0 -save-temps -fno-asynchronous-unwind-tables -fverbose-asm -masm=intel
CFLAGS := -Wall -O0 -save-temps -fno-asynchronous-unwind-tables -fverbose-asm

clean:
	${RM} *.o *.i *.s
