FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
  iproute2 \
  iputils-ping \
  iptables \
  traceroute \
  tcpdump \
  dnsmasq \
  netcat-openbsd \
  python3 \
  curl \
  wget \
  gawk \
  dnsutils \
  procps \
  isc-dhcp-client \
  vim
