@startuml
title ECサイトユースケース図
' システム境界には package を四角形の形式で利用する
skinparam packageStyle rectangle
' 図を水平に展開する命令

left to right direction
actor コンシューマー
actor 運営者
actor サプライヤー

package 運営者用管理画面 {
  運営者 -- (ログイン機能_m)
  運営者 -- (サプライヤー管理機能_m)
  運営者 -- (コンシューマー管理機能_m)
  運営者 -- (マスタ管理機能_m)
}

package サプライヤー用管理画面 {
  (ログイン機能_s) -- 運営者
  (商品登録機能_s) -- 運営者
  (カテゴリ・属性管理機能_s) -- 運営者
  サプライヤー -- (購入管理機能_s)
  サプライヤー -- (配送管理機能_s)
  (在庫管理機能_s) -- 運営者
  サプライヤー -- (売上管理機能_s)
  サプライヤー -- (レポート管理機能_s)
}

package コンシューマー用画面 {
  コンシューマー  -- (新規登録機能_c)
  コンシューマー  -- (ログイン機能_c)
  コンシューマー  -- (商品一覧機能_c)
  コンシューマー  -- (商品検索機能_c)
  (商品購入機能_c)
  コンシューマー  -- (購入履歴閲覧機能_c)
  コンシューマー  -- (支払い方法編集機能_c)
}

package (商品購入機能_c) {
  コンシューマー  -- (住所入力画面)
  コンシューマー  -- (配送方法選択画面)
  コンシューマー  -- (支払い情報入力画面)
  コンシューマー  -- (購入確認画面)
  コンシューマー  -- (購入完了画面)
}

@enduml
