CC := gcc
CFLAGS := -Wall -O0 -save-temps -fno-asynchronous-unwind-tables -fverbose-asm
EXISTSFILE := equalseq equalseq-practice equalseq-practice-2 sentinel

clean:
	${RM} ${EXISTSFILE} *.o *.i *.s *.bc
